import type React from "react";
import type { Metadata } from "next";
import { inter } from "@/components/ui/fonts";
import "reactflow/dist/style.css";
import "@/styles/globals.css";

import StoreProvider from "@/hooks/store-provider";

export const metadata: Metadata = {
    title: "Penflow",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={`${inter.className} antialiased`}>
                <StoreProvider>
                    {children}
                </StoreProvider>
            </body>
        </html>
    );
}
